name: Merge on main
on:
  pull_request:
    branches:
      - main
    types: [ closed ]
    steps:
      # Checkout code
      - name: Checkout Code
          if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
          uses: actions/checkout@v2
          
      - name: Commit files
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: |
          cd .\projects\prezevents-lib
          npm version patch
          cd ..\..
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Release [skip-ci]" -a || true    

      - name: Deploy
          if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          run: |
            npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN 
      - name: Push changes
          if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
          uses: ad-m/github-push-action@main
          with:
            github_token: ${{ secrets.ACTION_AUTH_TOKEN }}
            tags: true
            force: true