name: Publish pezevents-lib
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
jobs:
    build_and_deploy_pezevents_lib:
      # Setup OS and Node Version
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # Latest nodes only
          node-version: [ 13.x ]
      steps:
      
        # Checkout code
        - uses: actions/checkout@v2
        - run: echo "::debug::whats going on?{github.event}"

        - name: patch pezevents-lib npm version
          working-directory: ./projects/pezevents-lib
          run: |
            npm version patch
            
        - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Release [skip-ci]" -a || true    

        - name: Deploy
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          working-directory: ./dist/pezevents-lib
          run: |
              npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
              npm publish

        - name: Push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git push   