name: Publish pezevents-lib
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
jobs:
    build_and_deploy:
      # Setup OS and Node Version
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # Latest nodes only
          node-version: [ 13.x ]
      steps:
      
        # Checkout code
        - name: Checkout Code
          uses: actions/checkout@v2
          run: echo "::debug::whats going on?{github.event}"
            
        - name: Commit files
          run: |
            cd .\projects\prezevents-lib
            npm version patch
            cd ..\..
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Release [skip-ci]" -a || true    

        - name: Deploy
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          run: |
              npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN 
        - name: Push changes
            if: github.event.pull_request.merged == true
            uses: ad-m/github-push-action@main
            with:
              github_token: ${{ secrets.ACTION_AUTH_TOKEN }}
              tags: true
              force: true