name: Publish pezevents-lib
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
jobs:
    build_and_deploy:
      # Setup OS and Node Version
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # Latest nodes only
          node-version: [ 13.x ]
      steps:
      
        # Checkout code
        - uses: actions/checkout@v2
        - name: Checkout Code
          run: echo "::debug::whats going on?{github.event}"
            
        - name: Commit files
          run: |
            cd ./projects/prezevents-lib
            npm version patch
            cd ../..
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Release [skip-ci]" -a || true    

        - name: Deploy
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          run: |
              npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
              cd ./dist/pezevents-lib
              npm publish
              cd ../..

        - name: Push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git push   